# Generated by Django 5.0.3 on 2024-04-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_habits_image_alter_interests_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='habits',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_habits', to='users.habits'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_interests', to='users.interests'),
        ),
    ]
