# Generated by Django 5.0.3 on 2024-04-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_habits_customuser_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='habits',
            field=models.ManyToManyField(blank=True, related_name='user_habits', to='users.habits'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users_interests', to='users.interests'),
        ),
    ]
