# Generated by Django 5.0.3 on 2024-07-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_friends_friends_favorits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorits',
            new_name='Favorites',
        ),
    ]
