# Generated by Django 5.0.3 on 2024-07-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_favorits_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='premium'),
        ),
    ]
