# Generated by Django 5.0.3 on 2024-09-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_carmodel_usercar_image_usercar_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercar',
            name='model',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.carbrand'),
        ),
        migrations.AddField(
            model_name='usercar',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.carmodel'),
        ),
    ]
