# Generated by Django 5.1.2 on 2024-10-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_usercar_model_carmodel_brand_usercar_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium_activate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
