# Generated by Django 5.0.3 on 2024-04-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='countries/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('MEN', 'Мужчина'), ('GIRL', 'Женщина')], default='MEN', max_length=15, null=True, verbose_name='Пол')),
                ('gender_search', models.CharField(blank=True, choices=[('SEARH_MEN', 'Мужчину'), ('SEARCH_GIRL', 'Женщину'), ('SEARCH_FAMILY', 'Семью')], default='SEARCH_GIRL', max_length=15, null=True, verbose_name='Ищу')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Город, Курорт')),
                ('days', models.IntegerField(blank=True, null=True, verbose_name='Количество дней')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Когда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание путешествия')),
                ('travel_now', models.BooleanField(blank=True, default=False, null=True, verbose_name='Уже путешествую')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
            },
        ),
    ]
