# Generated by Django 5.0.3 on 2024-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cities',
            field=models.ManyToManyField(blank=True, null=True, related_name='city_countries', to='users.city', verbose_name='Города'),
        ),
    ]
