# Generated by Django 5.0.3 on 2024-04-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_alter_country_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default='Мужчина', max_length=15, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='gender_search',
            field=models.CharField(blank=True, choices=[('Мужчину', 'Мужчину'), ('Женщину', 'Женщину'), ('Семью', 'Семью')], default='Женщину', max_length=15, null=True, verbose_name='Ищу'),
        ),
    ]
