# Generated by Django 5.0.3 on 2024-04-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_alter_travel_gender_alter_travel_gender_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='country',
        ),
        migrations.AddField(
            model_name='travel',
            name='country',
            field=models.ManyToManyField(related_name='travels', to='travels.country', verbose_name='Страна'),
        ),
    ]
