# Generated by Django 5.1.2 on 2025-02-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_remove_travel_country_travel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default=None, max_length=15, null=True, verbose_name='Пол'),
        ),
    ]
