# Generated by Django 5.1.2 on 2025-02-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_alter_travel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='gender_search',
            field=models.CharField(blank=True, choices=[('Мужчину', 'Мужчину'), ('Женщину', 'Женщину'), ('Семью', 'Семью')], default=None, max_length=15, null=True, verbose_name='Ищу'),
        ),
    ]
