# Generated by Django 5.0.3 on 2024-07-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_dialog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='messages',
            field=models.ManyToManyField(related_name='messages_list', to='chat.message'),
        ),
    ]
