# Generated by Django 5.0.3 on 2024-08-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='finish',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
