# Generated by Django 5.0.3 on 2024-08-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_citiin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='citiin',
            new_name='cityin',
        ),
    ]
