# Generated by Django 5.0.3 on 2024-08-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_trip_trip_animals_trip_trip_baggage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/brands/%Y/%m/%d/'),
        ),
    ]
