# Generated by Django 5.0.3 on 2024-08-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_carbrand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='image',
            field=models.ImageField(upload_to='cars/brands/%Y/%m/%d/'),
        ),
    ]
