# Generated by Django 5.0.3 on 2024-09-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_alter_trip_city_alter_trip_cityin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='trips/others/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Дополнительная опция',
                'verbose_name_plural': 'Дополнительные опции',
            },
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_animals',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_baggage',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_hild_seat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_smoking',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_others',
            field=models.ManyToManyField(blank=True, null=True, related_name='trip_others', to='trips.tripother'),
        ),
    ]
