# Generated by Django 5.0.3 on 2024-09-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_tripother_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_date',
        ),
    ]
