# Generated by Django 5.0.3 on 2024-09-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_remove_trip_trip_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='tipr_users',
            new_name='trip_users',
        ),
    ]
