# Generated by Django 5.0.3 on 2024-09-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_rename_tipr_users_trip_trip_users'),
        ('users', '0012_carbrand_usercar_customuser_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercar',
            name='car',
        ),
        migrations.RemoveField(
            model_name='usercar',
            name='model',
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usercar'),
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='UserCar',
        ),
    ]
